### ISSUE TITLE
.net 4.7/4.8 support

### ISSUE THREAD

**Issue by akeilox** [actually-akac/AbuseIPDB#2]
I have an existing site/cms which runs on .net 4.8.2
would it be possible to include support for (slightly) older .net? I have tried but it seems to be detailed.

**Comment by akacdev** [comment]
Hi, thank you for opening this issue.
Generally, I only prefer to target the modern NET 6.0 and above, downgrading to add support for .NET Framework 4.7 and 4.8 would require lots of code refactoring backwards. You are free to clone the repository and do the necessary migration yourself.

**Comment by akeilox** [comment]
understood, It looks beyond me at the moment.
cheers
